name: bax-insiders
adopt-info: bax-insiders
summary: Code editing. Redefined.
description: |
  Binary releases of Visual Studio Code without branding/telemetry/licensing

base: core20
grade: stable
confinement: classic
compression: lzo

parts:
  bax-insiders:
    plugin: nil
    override-build: |
      set -eu
      # Get .deb url
      wget --quiet https://api.github.com/repos/Erg69/BAX-IDE-insiders/releases -O latest.json
      VERSION=$( jq -r 'sort_by(.tag_name|split(".")|map(tonumber))|last.tag_name' latest.json )
      DEB_URL=$( jq -r 'map(select(.tag_name == "'"${VERSION}"'"))|first.assets[].browser_download_url|select(endswith("'"_${SNAPCRAFT_TARGET_ARCH}.deb"'"))' latest.json )
      DEB_NAME=$( basename "${DEB_URL}" )
      # Downloading .deb
      wget "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB_NAME}"
      # Unpacking .deb
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB_NAME}" "${SNAPCRAFT_PART_INSTALL}"
      # Clean up
      rm -f latest.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB_NAME}"
      # Set version
      snapcraftctl set-version "${VERSION}"
      # Prepare GUI
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/meta/gui"
      cp "${SNAPCRAFT_PART_INSTALL}/usr/share/bax-insiders/resources/app/resources/linux/code.png" "${SNAPCRAFT_PART_INSTALL}/meta/gui/bax-insiders.png"
      # Update paths
      sed -i 's|Exec=/usr/share/bax/bax-insiders|Exec=bax-insiders --force-user-env|g' "${SNAPCRAFT_PART_INSTALL}/usr/share/applications/bax-insiders.desktop"
      sed -i 's|Exec=/usr/share/bax/bax-insiders|Exec=bax-insiders --force-user-env|g' "${SNAPCRAFT_PART_INSTALL}/usr/share/applications/bax-insiders-url-handler.desktop"
      sed -i 's|Icon=bax-insiders|Icon=${SNAP}/meta/gui/bax-insiders.png|g' "${SNAPCRAFT_PART_INSTALL}/usr/share/applications/bax-insiders.desktop"
      sed -i 's|Icon=bax-insiders|Icon=${SNAP}/meta/gui/bax-insiders.png|g' "${SNAPCRAFT_PART_INSTALL}/usr/share/applications/bax-insiders-url-handler.desktop"
    build-packages:
      - wget
      - jq
    stage:
      - -usr/share/bax/chrome-sandbox

layout:
  /usr/share/bax-insiders:
    bind: $SNAP/usr/share/bax-insiders

apps:
  bax:
    command: electron-launch $SNAP/usr/share/bax-insiders/bin/bax-insiders --no-sandbox
    desktop: usr/share/applications/bax-insiders.desktop
    common-id: bax-insiders.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
  url-handler:
    command: electron-launch $SNAP/usr/share/bax-insiders/bin/bax-insiders --open-url --no-sandbox
    desktop: usr/share/applications/bax-insiders-url-handler.desktop
